import React from 'react'

const JankotiLogo = ({ size = 'md', variant = 'default', className = '' }) => {
  const sizes = {
    sm: 'text-sm',
    md: 'text-base',
    lg: 'text-lg',
    xl: 'text-xl'
  }

  const variants = {
    default: 'text-violet-600',
    white: 'text-white',
    dark: 'text-gray-800',
    gradient: 'bg-gradient-to-r from-violet-600 to-fuchsia-600 bg-clip-text text-transparent'
  }

  return (
    <div className={`flex items-center gap-2 font-bold ${sizes[size]} ${className}`}>
      <div className="relative">
        <span className="text-2xl">🚀</span>
        <div className="absolute -top-1 -right-1 w-2 h-2 bg-gradient-to-r from-violet-500 to-fuchsia-500 rounded-full animate-pulse"></div>
      </div>
      <span className={`font-extrabold tracking-wider ${variants[variant]}`}>
        JANKOTI
      </span>
      <span className="text-xs opacity-75 font-normal">AI</span>
    </div>
  )
}

export const JankotiBranding = ({ className = '' }) => {
  return (
    <div className={`text-center ${className}`}>
      <JankotiLogo size="sm" variant="gradient" />
      <p className="text-xs text-gray-500 mt-1">AI-Powered Resume Builder</p>
    </div>
  )
}

export const JankotiWatermark = ({ className = '' }) => {
  return (
    <div className={`text-xs text-gray-400 opacity-60 ${className}`}>
      <div className="flex items-center justify-center gap-1">
        <span>🚀</span>
        <span>Generated by</span>
        <span className="font-semibold">JANKOTI</span>
        <span>AI Interview Platform</span>
      </div>
    </div>
  )
}

export default JankotiLogo